<?php


namespace app\components;


use yii\base\DynamicModel;
use yii\base\UserException;
use yii\web\UploadedFile;

/**
 * Class UploadComponent
 * @package app\components
 */
class UploadComponent extends \yii\base\Component
{
	/**
	 * @var string 文件存储路径
	 */
	public string $path;
	/**
	 * @var string 文件访问地址
	 */
	public string $host;
	/**
	 * @var int 数量限制
	 */
	public int $limit = 10;
	/**
	 * @var int 大小限制
	 */
	public int $size = 1024;
	/**
	 * @var string[]|null 文件类型限制
	 */
	public ?array $extensions = null;
	/**
	 * @var string[] 文件mime类型限制
	 * image/jpeg, image/png
	 */
	public array $mimeTypes = ['*'];

	public function init()
	{
		parent::init(); // TODO: Change the autogenerated stub
	}

	/**
	 * @param $model
	 * @param $attribute
	 * @return UploadedFile|null
	 */
	public function getFileByModelAttribute($model, $attribute)
	{
		return UploadedFile::getInstance($model, $attribute);
	}

	/**
	 * @param $name
	 * @return UploadedFile|null
	 */
	public function getFileByName($name)
	{
		return UploadedFile::getInstanceByName($name);
	}

	/**
	 * @param $uploadedFile
	 * @throws \yii\base\InvalidConfigException
	 */
	public function validate($uploadedFile)
	{
		DynamicModel::validateData(['file' => $uploadedFile], [
			['file', 'file', 'skipOnEmpty' => false, 'extensions' => $this->extensions, 'maxSize' => $this->size, 'maxFiles' => $this->limit, 'mimeTypes' => $this->mimeTypes]
		]);
	}

	/**
	 * @param $model
	 * @param $attribute
	 * @param $saveAs
	 * @param bool $validate
	 * @return UploadedFile|null
	 * @throws \yii\base\InvalidConfigException
	 */
	public function save($model, $attribute, $saveAs, $validate = true)
	{
		if (is_null($model)) {
			$uploadedFile = $this->getFileByName($attribute);
		} else {
			$uploadedFile = $this->getFileByModelAttribute($model, $attribute);
		}
		if ($validate) {
			$this->validate($uploadedFile);
		}
		$absolutePath = $this->path . $saveAs . '.' . $uploadedFile->extension;
		$absoluteDir = dirname($absolutePath);
		if (!is_dir($absoluteDir)) {
			mkdir($absoluteDir, 0777, true);
		}
		$uploadedFile->saveAs($absolutePath);
		return $uploadedFile;
	}
}