<?php

namespace app\models;

use Faker\Provider\Uuid;
use Yii;
use yii\helpers\ArrayHelper;
use yii\web\UploadedFile;

/**
 * This is the model class for table "{{%files}}".
 *
 * @property int $id
 * @property string $type 文件类型
 * @property string $name 文件名
 * @property string|null $path 文件路径
 * @property int|null $width 幅面宽
 * @property int|null $height 幅面高
 * @property string|null $description 说明
 */
class File extends \yii\db\ActiveRecord
{
	public UploadedFile $file;

	public array $uploadSet = [];

	public function init()
	{
		parent::init(); // TODO: Change the autogenerated stub
		$this->uploadSet = ArrayHelper::getValue(Yii::$app->params, 'upload') ?: [];
	}

	/**
	 * {@inheritdoc}
	 */
	public static function tableName()
	{
		return '{{%files}}';
	}

	/**
	 * {@inheritdoc}
	 */
	public function rules()
	{
		$fileRule = ['file', 'file'];
		$fileRuleSet = $this->uploadSet;
		unset($fileRuleSet['path']);
		unset($fileRuleSet['url']);
		$fileRule = array_merge($fileRule, $fileRuleSet);
		return [
			[['width', 'height'], 'integer'],
			[['type'], 'string', 'max' => 32],
			[['name', 'path', 'description'], 'string', 'max' => 255],
			$fileRule
		];
	}

	/**
	 * {@inheritdoc}
	 */
	public function attributeLabels()
	{
		return [
			'id' => 'ID',
			'type' => '文件类型',
			'name' => '文件名',
			'path' => '文件路径',
			'width' => '幅面宽',
			'height' => '幅面高',
			'description' => '说明',
		];
	}

	public function upload()
	{
		if ($this->validate()) {
			$uploadPath = $this->uploadSet['path'];
			$directory = date('Y/m/d');
			$uploadRelativePath = DIRECTORY_SEPARATOR . $directory . DIRECTORY_SEPARATOR . Uuid::uuid() . '.' . $this->file->extension;
			$uploadAbsolutePath = $uploadPath . $uploadRelativePath;
			$uploadAbsoluteDir = dirname($uploadAbsolutePath);
			if (!is_dir($uploadAbsoluteDir)) {
				mkdir($uploadAbsoluteDir, 0777, true);
			}
			$this->file->saveAs($uploadAbsolutePath);
			$this->path = $uploadRelativePath;
			$this->save();
			return $this;
		} else {
			return false;
		}
	}

	public function remove()
	{
		$uploadedFilePath = str_replace('/', DIRECTORY_SEPARATOR, $this->uploadSet['path'] . $this->path);
		if (file_exists($uploadedFilePath)) {
			@unlink($uploadedFilePath);
			return true;
		}
		return false;
	}

	public function getPath()
	{
		return str_replace('\\', DIRECTORY_SEPARATOR, $this->uploadSet['path'] . $this->path);
	}

	public function getUrl()
	{
		return str_replace(DIRECTORY_SEPARATOR, '/', $this->uploadSet['url'] . $this->path);
	}
}
